# Generated by Django 3.0.2 on 2020-02-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shivam', '0002_auto_20200202_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roomno',
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(max_length=4),
        ),
    ]
